#!/usr/bin/env zsh

set -euo pipefail

projects=$(jq --raw-output '.projects | keys | .[]' ~/dev/projects.json)

project=$(dmenu <<<$projects)

projectpath=$(jq --raw-output ".projects[\"$project\"].path" ~/dev/projects.json)

terminal --working-directory $projectpath
