#!/usr/bin/env zsh

TIME=$(date "+%H%M")
zzz=$'💤\uFE0E'

if (($TIME > 0100 && $TIME < 0800))
then
	if (($TIME > 0230))
	then
		echo "$zzz sleep"
		exit 33
	elif (($TIME > 0200))
	then
		echo "$zzz sleep"
		exit 32
	else
		echo "$zzz sleep"
		exit 31
	fi

	exit
fi

echo ""
#echo "⭕ <span color='#ffffff'>todo</span> (0/1)"
#echo "✅ <span color='#ffffff'>done</span> (0/1)"
