#!/usr/bin/env zsh

TIME=$(date "+%H%M")
zzz=$'💤\uFE0E'

if (($TIME > 0100 && $TIME < 0800))
then
	if (($TIME > 0230))
	then
		echo "<active><critical>$zzz sleep</critical></active>"
	elif (($TIME > 0200))
	then
		echo "<active><error>$zzz sleep</error></active>"
	else
		echo "<active><warning>$zzz sleep</warning></active>"
	fi

	exit
fi

echo ""
#echo "⭕ <span color='#ffffff'>todo</span> (0/1)"
#echo "✅ <span color='#ffffff'>done</span> (0/1)"
