#!/usr/bin/env zsh

TIME=$(date "+%H%M")

if (($TIME > 0100 && $TIME < 0800))
then
	if (($TIME > 0230))
	then
		echo "<span color='#000000' background='#ff2200'>💤 sleep</span>"
	elif (($TIME > 0200))
	then
		echo "<span color='#ff4400'>💤 sleep</span>"
	else
		echo "<span color='#ff8800'>💤 sleep</span>"
	fi

	exit
fi

echo ""
#echo "⭕ <span color='#ffffff'>todo</span> (0/1)"
#echo "✅ <span color='#ffffff'>done</span> (0/1)"
