#!/usr/bin/env bash

if [[ -n "${1}" ]]
then
	INTERFACE="${1}"
else
	INTERFACE="${BLOCK_INSTANCE:-wlp2s0}"
fi

SSID=$(iwgetid -r)

# don't display if there is no active wifi adapter
[[ ! -d /sys/class/net/${INTERFACE}/wireless ]] ||
  [[ "$(cat /sys/class/net/$INTERFACE/operstate)" = 'down' ]] && exit

QUALITY=$(grep $INTERFACE /proc/net/wireless | awk '{ print int($3 * 100 / 70) }')

[[ "$SSID" = 100111010110 ]] && SSID="<span color='#44ccff'>$SSID</span>"

echo "${SSID} $QUALITY%"

# color
if (( $QUALITY <= 20 )); then
    exit 29
elif (( $QUALITY <= 30 )); then
    exit 28
elif (( $QUALITY <= 40 )); then
    exit 27
fi
