#!/usr/bin/env zsh

set -euo pipefail

case ${1:---print-config} in
  --watch)
    echo ${0:a} | entr ${0:a} --apply
    exit $?
    ;;
  --apply)
    swaymsg_cmd=$(command -v swaymsg)
    is_apply=true
    ;;
  --print-config)
    swaymsg_cmd=echo
    is_apply=false
    ;;
  *)
    echo "Invalid argument" >&2
    exit 1
    ;;
esac

function swaymsg {
  $swaymsg_cmd $@
}

# Bg Shades
sumiInk0='#16161D'
sumiInk1b='#181820'
sumiInk1='#1F1F28'
sumiInk2minus='#262632'
sumiInk2='#2A2A37'
sumiInk2plus='#2E2E3C'
sumiInk3='#363646'
sumiInk4='#54546D'

# Popup and Floats
waveBlue1='#223249'
waveBlue2='#2D4F67'

# Diff and Git
winterGreen='#2B3328'
winterYellow='#49443C'
winterRed='#43242B'
winterBlue='#252535'
autumnGreen='#76946A'
autumnRed='#C34043'
autumnYellow='#DCA561'

# Diag
samuraiRed='#E82424'
roninYellow='#FF9E3B'
waveAqua1='#6A9589'
dragonBlue='#658594'

# Fg and Comments
oldWhite='#C8C093'
fujiWhite='#DCD7BA'
fujiGray='#727169'
springViolet1='#938AA9'

oniViolet='#957FB8'
crystalBlue='#7E9CD8'
springViolet2='#9CABCA'
springBlue='#7FB4CA'
lightBlue='#A3D4D5'
waveAqua2='#7AA89F'

# waveAqua2='#68AD99'
# waveAqua4='#7AA880'
# waveAqua5='#6CAF95'
# waveAqua3='#68AD99'

springGreen='#98BB6C'
boatYellow1='#938056'
boatYellow2='#C0A36E'
carpYellow='#E6C384'

sakuraPink='#D27E99'
waveRed='#E46876'
peachRed='#FF5D62'
surimiOrange='#FFA066'
katanaGray='#717C7C'


inverted_fg=$sumiInk0

active_bg=$sumiInk2plus
active_fg=$oniViolet
active_border=$active_bg

inactive_bg=$sumiInk2minus
inactive_fg=$sumiInk4
inactive_border=$inactive_bg

urgent_bg=$surimiOrange
urgent_fg=$inverted_fg

gaps=4
swaymsg gaps inner $gaps
swaymsg gaps outer "'-$gaps'"
$is_apply && {
  swaymsg gaps inner all set $gaps
  swaymsg gaps outer all set "'-$gaps'"
}
swaymsg smart_gaps off
swaymsg default_border normal 0
swaymsg default_floating_border normal 0
swaymsg titlebar_border_thickness 0


swaymsg client.focused $active_border $active_bg $active_fg $active_bg $active_border

swaymsg client.focused_inactive $inactive_border $inactive_bg $inactive_fg $inactive_bg $inactive_border
# defaults to focused_inactive
swaymsg client.focused_tab_title $inactive_border $inactive_bg $inactive_fg

swaymsg client.unfocused $inactive_border $inactive_bg $inactive_fg $inactive_bg $inactive_border

swaymsg client.urgent $urgent_bg $urgent_bg $urgent_fg

bar_fg=$katanaGray
bar_bg=$sumiInk0
bar_selection=$oniViolet

swaymsg bar bar-0 colors background $bar_bg
swaymsg bar bar-0 colors statusline $bar_fg
swaymsg bar bar-0 colors separator $sumiInk4

# focused_workspace
#swaymsg bar bar-0 colors focused_workspace $bar_selection $bar_selection $inverted_fg
swaymsg bar bar-0 colors focused_workspace $bar_selection $sumiInk1 $bar_selection

# active_workspace
#swaymsg bar bar-0 colors active_workspace $crystalBlue $sumiInk1 $crystalBlue
swaymsg bar bar-0 colors active_workspace $bar_fg $sumiInk1 $bar_fg

swaymsg bar bar-0 colors inactive_workspace $sumiInk1 $sumiInk1 $bar_fg
swaymsg bar bar-0 colors urgent_workspace $sumiInk4 $urgent_bg $urgent_fg
#swaymsg bar bar-0 colors binding_mode $waveRed $waveRed $inverted_fg
swaymsg bar bar-0 colors binding_mode $sakuraPink $sakuraPink $inverted_fg
